[package]
name = "analytics-module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5" 